In [1]:
import numpy  as np
import pandas as pd

In [ ]:
data = pd.read_csv('train.csv')

In [5]:
data.shape

(2000, 21)

In [6]:
data.head()

,battery_power,blue,clock_speed,dual_sim,fc,four_g,int_memory,m_dep,mobile_wt,n_cores,...,px_height,px_width,ram,sc_h,sc_w,talk_time,three_g,touch_screen,wifi,price_range
0,842,0,2.2,0,1,0,7,0.6,188,2,...,20,756,2549,9,7,19,0,0,1,1
1,1021,1,0.5,1,0,1,53,0.7,136,3,...,905,1988,2631,17,3,7,1,1,0,2
2,563,1,0.5,1,2,1,41,0.9,145,5,...,1263,1716,2603,11,2,9,1,1,0,2
3,615,1,2.5,0,0,0,10,0.8,131,6,...,1216,1786,2769,16,8,11,1,0,0,2
4,1821,1,1.2,0,13,1,44,0.6,141,2,...,1208,1212,1411,8,2,15,1,1,0,1

In [23]:
x = data.iloc[:, :-1] # Contains all Features
y = data.iloc[:, -1]  # Contains the Target Variable

In [8]:
x.shape

(2000, 20)

In [9]:
mu = x.mean(axis=0)
sigma = x.std(axis=0)
x = (x - mu) / sigma

In [10]:
from sklearn.feature_selection import SelectKBest

In [12]:
bestfeatures = SelectKBest()
fit = bestfeatures.fit(x,y)

In [13]:
fit.scores_

array([3.15981575e+01, 4.76767709e-01, 4.93707801e-01, 4.28239286e-01,
       7.72181960e-01, 1.05952453e+00, 2.92299608e+00, 1.50068244e+00,
       3.59431819e+00, 2.62541515e+00, 8.25446358e-01, 1.94848418e+01,
       2.26208825e+01, 3.52011082e+03, 2.22598374e+00, 1.67099983e+00,
       1.62881131e+00, 4.57319750e-01, 1.29330223e+00, 2.84940470e-01])

In [14]:
dfscores = pd.DataFrame(fit.scores_)
dfcolumns = pd.DataFrame(x.columns)

In [15]:
featuresScores = pd.concat([dfcolumns,dfscores],axis=1)
featuresScores.columns = ['Feature','Score']

In [16]:
featuresScores

          Feature        Score
0   battery_power    31.598158
1            blue     0.476768
2     clock_speed     0.493708
3        dual_sim     0.428239
4              fc     0.772182
5          four_g     1.059525
6      int_memory     2.922996
7           m_dep     1.500682
8       mobile_wt     3.594318
9         n_cores     2.625415
10             pc     0.825446
11      px_height    19.484842
12       px_width    22.620882
13            ram  3520.110824
14           sc_h     2.225984
15           sc_w     1.671000
16      talk_time     1.628811
17        three_g     0.457320
18   touch_screen     1.293302
19           wifi     0.284940

In [46]:
featuresScores = featuresScores.sort_values(by='Score', ascending=False)

Lets take top 10 features

In [47]:
top10 = list(featuresScores[:10]['Feature'].values)
top10

['ram',
 'battery_power',
 'px_width',
 'px_height',
 'mobile_wt',
 'int_memory',
 'n_cores',
 'sc_h',
 'sc_w',
 'talk_time']

In [33]:
#Model Comparison
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline

In [48]:
model = make_pipeline(
    StandardScaler(),
    LogisticRegression(max_iter=1000)
)
model.fit(x, y)

Pipeline(steps=[('standardscaler', StandardScaler()),
                ('logisticregression', LogisticRegression(max_iter=1000))])

In [49]:
scores = cross_val_score(model, x, y, cv=10)
scores.mean()

np.float64(0.9620000000000001)

Now use only top 10 features

In [50]:
scores = cross_val_score(model, x[top10], y, cv=10)
scores.mean()

np.float64(0.9710000000000001)

Scores improve here