**One Hot Encoding**  
One-hot encoding is a data preprocessing technique that converts categorical data (like 'Red', 'Green', 'Blue') into a numerical format for machine learning models by creating new binary columns for each unique category, assigning a '1' in the corresponding column and '0' in others, preventing models from misinterpreting categories as having an order or magnitude.

**How it works**  
Identifies Categories: Finds all unique values (e.g., 'Apple', 'Banana', 'Mango') in a categorical column.  
Creates New Columns: Generates a new binary column for each unique category.  
Assigns Binary Values: For each original data point, places a '1' in the new column corresponding to its category and '0' in all other new columns.

**Why it's used**
Numerical Input: Most ML algorithms require numerical input.  
No False Order: Prevents models from assuming an order (e.g., 'Apple' < 'Banana') that doesn't exist, which can happen with simple integer encoding.  
Handles Nominal Data: Ideal for nominal (unranked) categorical data like colors, cities, or types.  

**Key Considerations**
Curse of Dimensionality: Can create too many features (columns) if a category has many unique values, potentially slowing models.  
Multicollinearity: Introduces dependency between the new columns, though often handled by dropping one category (e.g., if it's not Apple or Banana, it must be Mango).

Example  
If you have a 'Fruit' column with 'Apple', 'Banana', 'Mango':  
Original: Apple, Banana, Mango  
One-Hot Encoded:    
Apple becomes  (Apple=1, Banana=0, Mango=0)    
Banana becomes (Apple=0, Banana=1, Mango=0)    
Mango becomes  (Apple=0, Banana=0, Mango=1)

**Why it's used**  
**Numerical Input**: Most ML algorithms require numerical input.  
**No False Order**: Prevents models from assuming an order (e.g., 'Apple' < 'Banana') that doesn't exist, which can happen with simple integer encoding.  
**Handles Nominal Data**: Ideal for nominal (unranked) categorical data like colors, cities, or types.

**Key Considerations**  
**Curse of Dimensionality** : Can create too many features (columns) if a category has many unique values, potentially slowing models.  
**Multicollinearity** : Introduces dependency between the new columns, though often handled by dropping one category (e.g., if it's not Apple or Banana, it must be Mango).

In [1]:
import numpy as np 
import pandas as pd

In [2]:
df = pd.read_csv('cars.csv')

In [3]:
df.head()

     brand  km_driven    fuel         owner  selling_price
0   Maruti     145500  Diesel   First Owner         450000
1    Skoda     120000  Diesel  Second Owner         370000
2    Honda     140000  Petrol   Third Owner         158000
3  Hyundai     127000  Diesel   First Owner         225000
4   Maruti     120000  Petrol   First Owner         130000

In [4]:
df['owner'].value_counts()

owner
First Owner             5289
Second Owner            2105
Third Owner              555
Fourth & Above Owner     174
Test Drive Car             5
Name: count, dtype: int64

In [6]:
df['fuel'].value_counts()

fuel
Diesel    4402
Petrol    3631
CNG         57
LPG         38
Name: count, dtype: int64

**OneHotEncoding using Pandas**

In [5]:
pd.get_dummies(df,columns=['fuel','owner'])

,brand,km_driven,selling_price,fuel_CNG,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_First Owner,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,False,True,False,False,True,False,False,False,False
1,Skoda,120000,370000,False,True,False,False,False,False,True,False,False
2,Honda,140000,158000,False,False,False,True,False,False,False,False,True
3,Hyundai,127000,225000,False,True,False,False,True,False,False,False,False
4,Maruti,120000,130000,False,False,False,True,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,False,True,True,False,False,False,False
8124,Hyundai,119000,135000,False,True,False,False,False,True,False,False,False
8125,Maruti,120000,382000,False,True,False,False,True,False,False,False,False
8126,Tata,25000,290000,False,True,False,False,True,False,False,False,False
8127,Tata,25000,290000,False,True,False,False,True,False,False,False,False

**K-1 OneHotEncoding**

In [7]:
pd.get_dummies(df,columns=['fuel','owner'],drop_first=True)

,brand,km_driven,selling_price,fuel_Diesel,fuel_LPG,fuel_Petrol,owner_Fourth & Above Owner,owner_Second Owner,owner_Test Drive Car,owner_Third Owner
0,Maruti,145500,450000,True,False,False,False,False,False,False
1,Skoda,120000,370000,True,False,False,False,True,False,False
2,Honda,140000,158000,False,False,True,False,False,False,True
3,Hyundai,127000,225000,True,False,False,False,False,False,False
4,Maruti,120000,130000,False,False,True,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
8123,Hyundai,110000,320000,False,False,True,False,False,False,False
8124,Hyundai,119000,135000,True,False,False,True,False,False,False
8125,Maruti,120000,382000,True,False,False,False,False,False,False
8126,Tata,25000,290000,True,False,False,False,False,False,False
8127,Tata,25000,290000,True,False,False,False,False,False,False

**OneHotEncoding using Sklearn**

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:4],df.iloc[:,-1],test_size=0.2,random_state=2)

In [9]:
X_train.head()

         brand  km_driven    fuel         owner
5571   Hyundai      35000  Diesel   First Owner
2038      Jeep      60000  Diesel   First Owner
2957   Hyundai      25000  Petrol   First Owner
7618  Mahindra     130000  Diesel  Second Owner
6684   Hyundai     155000  Diesel   First Owner

In [15]:
y_train.head()

5571    1150000
2038    1689999
2957     580000
7618     150000
6684     320000
Name: selling_price, dtype: int64

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [12]:
ohe = OneHotEncoder(drop='first',dtype=np.int32)

In [13]:
X_train_new = ohe.fit_transform(X_train[['fuel','owner']])

In [14]:
X_test_new = ohe.transform(X_test[['fuel','owner']])

In [24]:
feature_names = ohe.get_feature_names_out(['fuel', 'owner'])

In [25]:
feature_names

array(['fuel_Diesel', 'fuel_LPG', 'fuel_Petrol',
       'owner_Fourth & Above Owner', 'owner_Second Owner',
       'owner_Test Drive Car', 'owner_Third Owner'], dtype=object)

In [23]:
X_train_new[:5].toarray()

array([[1, 0, 0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0],
       [1, 0, 0, 0, 1, 0, 0],
       [1, 0, 0, 0, 0, 0, 0]], dtype=int32)

**OneHotEncoding with Top Categories**

In [26]:
counts = df['brand'].value_counts()

In [27]:
df['brand'].nunique()
threshold = 100

In [28]:
repl = counts[counts <= threshold].index

In [29]:
pd.get_dummies(df['brand'].replace(repl, 'uncommon')).sample(5)

,BMW,Chevrolet,Ford,Honda,Hyundai,Mahindra,Maruti,Renault,Skoda,Tata,Toyota,Volkswagen,uncommon
3185,False,False,False,False,True,False,False,False,False,False,False,False,False
6163,False,False,False,False,False,False,False,False,False,False,False,False,True
1510,False,False,False,False,False,False,False,False,False,False,False,True,False
5710,True,False,False,False,False,False,False,False,False,False,False,False,False
5690,False,False,False,False,True,False,False,False,False,False,False,False,False